---
- hosts: test2
  vars:
    http_port: 80
    max_clients: 200
  remote_user: colony
  sudo: yes
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: install php
    shell: yum install -y php php-fpm php-mysql

  - name: Copy ansible inventory file to client
    copy: src=/var/.ansible/playbooks/mysql-community-release-el7-5.noarch.rpm dest=/tmp/mysql-community-release-el7-5.noarch.rpm
            owner=root group=root mode=0700
  - name:
    yum:
      name: /tmp/mysql-community-release-el7-5.noarch.rpm
      state: latest

  - name: rm rpm
    shell: rm -fr /tmp/mysql-community-release-el7-5.noarch.rpm

  - name: install mysql-server
    yum:
      name: mysql-community-server
      state: latest
  - name: install mysql mysql-devel
    shell: yum install -y mysql mysql-devel
 

  - name: ensure nginx is running
    service:
      name: nginx
      state: started
      enabled: true
  - name: ensure php-fpm is running
    service:
      name: php-fpm
      state: started
      enabled: true
  - name: ensure mysqld is running
    service:
      name: mysqld
      state: started
      enabled: true
#ansible-playbook one.yml
#yum模块:
#       name：要进行操作的软件包的名字，也可以传递一个url或者一个本地的rpm包的路径 
#       state：状态（present，absent，latest）
#
#copy模块:
#       backup：在覆盖之前将原文件备份，备份文件包含时间信息。有两个选项：yes|no
#       dest:   要将源文件复制到的远程主机的绝对路径，如果源文件是一个目录，那么该路径也必须是个目录
#       src:    要复制到远程主机的文件在本地的地址，可以是绝对路径，也可以是相对路径。如果路径是一个目录，它将递归复制。在这种情况下，如果路径使用"/"来结尾，则只复制目录里的内容，如果没有使用"/"来结尾，则包含目录在内的整个内容全部复制，类似于rsync
#
